<package format="3">
    <name>raphael_robot_controllers</name>
    <version>0.0.1</version>
    <description>Custom controllers for Raphael Robot</description>
    <maintainer email="you@example.com">You</maintainer>
    <license>Apache-2.0</license>

    <!-- 构建工具 -->
    <buildtool_depend>ament_cmake</buildtool_depend>

    <!-- 核心依赖 -->
    <depend>rclcpp</depend>
    <depend>rclcpp_lifecycle</depend>
    <depend>controller_interface</depend>
    <depend>example_interfaces</depend>
    <depend>pluginlib</depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>