controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_driver_controller:
      type: diff_drive_controller/DiffDriveController

    snake_driver_controller:
      type: forward_command_controller/ForwardCommandController

#    snake_driver_controller_mock:
#      type: forward_command_controller/ForwardCommandController

diff_driver_controller:
  ros__parameters:
    left_wheel_names: [ "base_left_wheel_joint" ]
    right_wheel_names: [ "base_right_wheel_joint" ]
    wheel_separation: 0.045
    wheel_radius: 0.01

    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    pose_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.01 ]
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.01 ]

    enable_odom_tf: true
    publish_rate: 50.0

    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0

    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0

snake_driver_controller:
  ros__parameters:
    joints: [ "s1_link06_link07_joint", "s1_link07_link08_joint", "s1_link08_link09_joint", "s1_link09b_link10_joint", "s1_link10_link11_joint" ]
    interface_name: "position"

#snake_driver_controller_mock:
#  ros__parameters:
#    joints: [ "base_s1_link00","s1_link01_link02_joint", "s1_link02_link03_joint", "s1_link03_link04_joint", "s1_link04_link05_joint", "s1_link05_link06_joint" ]
#    interface_name: "position"